"""
Player Interface — filtered view of game state.

The Player Interface is NOT a separate copy of state.
It is a read/write gateway that:
  - SHOWS players only what their character perceives
  - HIDES: DM notes, hidden secrets, other players' private info, unexplored areas
  - ROUTES all actions through the engine (players never mutate state directly)
  - GATES some information behind skill checks / in-character discovery

Design principle:
  The engine owns truth. The player interface is a lens, not a copy.
  If the player interface needs to "lie" to a player, it does so through
  narrative description generated by the LLM — not by mutating state.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from dnd_core.models import (
    Ability,
    Campaign,
    CharacterSheet,
    Entity,
    GameSession,
    Location,
    NPC,
    Quest,
    WorldState,
)
from dnd_core.state_machine import GameStateMachine


# ─── What the player can see ────────────────────────────────────────────────────

@dataclass
class PlayerViewCharacter:
    """
    The player-character-facing view of a character sheet.
    Omits: DM-only notes, hidden conditions, secret quest flags.
    """
    id: str
    name: str
    hp: int
    hp_max: int
    ac: int
    level: int
    class_name: str
    race: str

    # Visible conditions only
    visible_conditions: list[str] = field(default_factory=list)

    # Exhaustion (visible at all levels per PHB)
    exhaustion_level: int = 0

    # Action economy (current turn)
    movement_remaining: int = 0
    has_action: bool = True
    has_bonus_action: bool = True
    has_reaction: bool = True

    # Resources the player tracks themselves
    spell_slots: dict[int, int] = field(default_factory=dict)  # {level: remaining}
    hit_dice: list[int] = field(default_factory=list)
    death_save_successes: int = 0
    death_save_failures: int = 0

    # Skills the player has (for their own reference)
    skill_bonuses: dict[str, int] = field(default_factory=dict)


@dataclass
class PlayerViewLocation:
    """
    What a player sees about a location.
    Based on visit status, skill checks, and what the LLM has revealed.
    """
    id: str
    name: str
    location_type: str

    # Description: revealed only after visiting / successful perception check
    description: str = ""
    description_revealed: bool = False

    # Connections: visible if explored or asked about
    known_exits: list[str] = field(default_factory=list)  # location names
    exits_revealed: bool = False

    # NPCs: only if met
    npcs_here: list[str] = field(default_factory=list)  # names only, no stats

    # Dangers: only if discovered
    known_dangers: list[str] = field(default_factory=list)


@dataclass
class PlayerViewNPC:
    """
    What a player sees about an NPC.
    Private DM notes and hidden motivations are NEVER exposed here.
    """
    id: str
    name: str
    role: str
    description: str

    # Disposition (as player perceives it)
    disposition: str = "neutral"

    # What the player has learned about this NPC
    known_traits: list[str] = field(default_factory=list)
    conversation_topics: list[str] = field(default_factory=list)  # what player has asked about

    # Quest-related
    quest_flag: Optional[str] = None   # "quest_available", "quest_giver", etc.


@dataclass
class PlayerViewWorld:
    """
    The world as the player perceives it.
    Strictly filtered: unexplored locations are absent, DM notes stripped.
    """
    locations: dict[str, PlayerViewLocation] = field(default_factory=dict)
    visited_location_ids: list[str] = field(default_factory=list)

    # Quests the player knows about
    active_quests: list[str] = field(default_factory=list)   # quest names only


@dataclass
class PlayerViewSession:
    """
    What the player sees about the current session.
    """
    game_date: str = ""
    mode: str = "exploring"
    active_location: Optional[PlayerViewLocation] = None
    active_npc: Optional[PlayerViewNPC] = None

    # Own character
    character: Optional[PlayerViewCharacter] = None

    # Party (other players' visible state)
    party: list[PlayerViewCharacter] = field(default_factory=list)

    # Last LLM narration
    last_narration: str = ""

    # What options the player can take right now
    available_actions: list[str] = field(default_factory=list)


# ─── Player Interface ───────────────────────────────────────────────────────────

class PlayerInterface:
    """
    The player's window into the game.

    Each player gets their own PlayerInterface instance, scoped to their
    character. They can never see:
      - Other players' character sheets (except public info)
      - DM notes, DM secrets, hidden quest objectives
      - Unexplored locations
      - Monster stat blocks they're not meant to see

    All state mutations go through here — the player never calls the engine
    or state machine directly. Instead they call player_* methods which
    route to the appropriate mechanical resolution and return a result.
    """

    def __init__(
        self,
        player_id: str,
        character: CharacterSheet,
        game_sm: GameStateMachine,
        campaign: Campaign,
    ) -> None:
        self.player_id = player_id
        self.character = character          # their own character sheet
        self.game_sm = game_sm
        self.campaign = campaign

        # Active quest knowledge (revealed objectives only)
        self._revealed_objectives: dict[str, list[str]] = {}  # quest_id → [revealed objective ids]

    # ── Read: build player views ─────────────────────────────────────────────

    def view(self) -> PlayerViewSession:
        """Return the full player-visible session state."""
        state = self.game_sm.state

        view = PlayerViewSession(
            game_date=state.turn_context.game_date,
            mode=state.mode.name.lower(),
            character=self._character_view(),
            last_narration=state.turn_context.scene_description,
            available_actions=self._available_actions(),
        )

        # Active location
        if state.turn_context.location_id:
            view.active_location = self._location_view(state.turn_context.location_id)

        # Active NPC
        if state.turn_context.current_npc_id:
            view.active_npc = self._npc_view(state.turn_context.current_npc_id)

        # Party
        for pc_id in self.campaign.player_character_ids:
            if pc_id == self.character.id:
                continue
            pc = self._find_pc(pc_id)
            if pc:
                view.party.append(self._character_view(pc))

        return view

    def _character_view(self, entity: Optional[Entity] = None) -> PlayerViewCharacter:
        """Build player view of a character sheet."""
        if entity is None:
            entity = self.character

        return PlayerViewCharacter(
            id=entity.id,
            name=entity.name,
            hp=entity.hp,
            hp_max=entity.hp_max,
            ac=entity.ac,
            level=getattr(entity, "level", 1),
            class_name=getattr(entity, "class_name", "Unknown"),
            race=getattr(entity, "race", "Unknown"),
            visible_conditions=[c.condition.name for c in entity.conditions],
            exhaustion_level=entity.exhaustion,
            movement_remaining=entity.economy.movement,
            has_action=entity.economy.action,
            has_bonus_action=entity.economy.bonus_action,
            has_reaction=entity.economy.reaction,
            spell_slots={i: entity.spell_slots.slot_max(i) for i in range(1, 10)},
            death_save_successes=entity.death_saves.successes,
            death_save_failures=entity.death_saves.failures,
            skill_bonuses={},  # TODO: fill from character class
        )

    def _location_view(self, location_id: str) -> Optional[PlayerViewLocation]:
        """Build player view of a location (respects exploration status)."""
        if self.campaign.world is None:
            return None

        loc = self.campaign.world.locations.get(location_id)
        if loc is None:
            return None

        revealed = loc.visit_status.value >= 2  # EXPLORED or HOME_BASE

        return PlayerViewLocation(
            id=loc.id,
            name=loc.name,
            location_type=loc.location_type.name.lower(),
            description=loc.description if revealed else "",
            description_revealed=revealed,
            known_exits=[],  # TODO: reveal connections after exploration
            exits_revealed=revealed,
            npcs_here=[],     # TODO: reveal NPCs after meeting them
            known_dangers=[], # TODO: reveal after perception / discovery
        )

    def _npc_view(self, npc_id: str) -> Optional[PlayerViewNPC]:
        """Build player view of an NPC (no DM notes ever)."""
        if self.campaign.world is None:
            return None

        # Find NPC in world
        # NPCs live in world state; implement lookup when NPC model is integrated
        return PlayerViewNPC(
            id=npc_id,
            name="Unknown",
            role="unknown",
            description="",
        )

    def _find_pc(self, pc_id: str) -> Optional[Entity]:
        """Find a player character by ID."""
        # TODO: player characters stored in campaign
        return None

    def _available_actions(self) -> list[str]:
        """
        List of actions the player can currently take.
        Derived from mode + action economy + equipment.
        """
        state = self.game_sm.state
        ctx = state.turn_context

        actions = []

        if state.mode == GameMode.EXPLORING:
            actions = ["move", "look", "interact", "talk", "search", "skill_check"]
        elif state.mode == GameMode.SOCIAL:
            actions = ["talk", "persuade", "intimidate", "insight", "deceive", "leave"]
        elif state.mode == GameMode.TRAVEL:
            actions = ["move", "look", "set_pace", "rest", "scan"]
        elif state.mode == GameMode.COMBAT:
            actions = ["attack", "cast_spell", "dash", "disengage", "dodge", "help",
                       "hide", "ready", "search", "use_object", "shove", "grapple"]
            if ctx.current_actor() == self.character:
                actions += ["end_turn"]

        return actions

    # ── Write: player actions (routed to engine) ────────────────────────────

    def player_attack(
        self,
        target_name: str,
        ability: Ability = Ability.STR,
        advantage: bool = False,
        disadvantage: bool = False,
    ) -> dict:
        """
        Player declares an attack. Engine resolves it.
        Returns structured result for LLM narration + UI update.
        """
        # Find target in combat
        target = self._find_combat_target(target_name)
        if target is None:
            return {"error": f"Target '{target_name}' not in combat."}

        # Engine handles the attack roll + damage
        # TODO: wire up engine

        return {"status": "pending", "message": "Attack not yet wired to engine."}

    def player_cast_spell(
        self,
        spell_name: str,
        level: int = 0,
        target: Optional[str] = None,
        save_ability: Optional[Ability] = None,
    ) -> dict:
        """Player casts a spell. Engine validates slots, resolves effects."""
        # TODO: wire up engine
        return {"status": "pending"}

    def player_skill_check(
        self,
        skill: str,
        difficulty: int = 10,
        advantage: bool = False,
        disadvantage: bool = False,
    ) -> dict:
        """Player attempts a skill check. Engine rolls and resolves."""
        # TODO: wire up engine
        return {"status": "pending"}

    def player_move(self, destination_id: str) -> dict:
        """Player moves to a location. Triggers exploration events."""
        # TODO: wire up engine
        return {"status": "pending"}

    def player_end_turn(self) -> list:
        """Player ends their turn. Engine advances combat."""
        return self.game_sm.next_turn()

    def _find_combat_target(self, name: str) -> Optional[Entity]:
        """Find a combatant by name in the current encounter."""
        state = self.game_sm.state
        if not state.is_combat():
            return None
        for entry in state.initiative_order:
            if entry.entity.name.lower() == name.lower():
                return entry.entity
        return None

    # ── Skill-gated information ─────────────────────────────────────────────

    def try_perception(self, target_location_id: str, difficulty: int = 10) -> dict:
        """
        Player uses perception. If they beat the DC, reveal hidden details.
        Called by engine, not directly by player — player just says 'look around'.
        """
        # TODO: wire to engine for roll + reveal logic
        return {"status": "pending"}


# ─── DM Interface ──────────────────────────────────────────────────────────────

class DMInterface:
    """
    The DM's window into the game. Sees everything, can modify everything.
    """

    def __init__(
        self,
        game_sm: GameStateMachine,
        campaign: Campaign,
        dm_notes: "DMNotes",
    ) -> None:
        self.game_sm = game_sm
        self.campaign = campaign
        self.dm_notes = dm_notes

    def full_state(self) -> SessionState:
        """Return the complete unfiltered session state."""
        return self.game_sm.state

    def world(self) -> WorldState:
        """Return the full world state."""
        return self.campaign.world or WorldState(world_id="", name="Empty World")

    # ── World building ───────────────────────────────────────────────────

    def create_location(self, location: Location) -> None:
        if self.campaign.world is None:
            self.campaign.world = WorldState(world_id=self.campaign.id, name=self.campaign.name)
        self.campaign.world.add_location(location)

    def reveal_location(self, location_id: str) -> None:
        """Mark a location as explored so players can see it."""
        if self.campaign.world:
            self.campaign.world.visit_location(location_id)

    # ── NPC management ───────────────────────────────────────────────────

    def add_npc(self, npc: NPC) -> None:
        """Add an NPC to the world."""
        # TODO: NPC registry in world state
        pass

    def meet_npc(self, npc_id: str) -> None:
        """Mark that the party has met this NPC."""
        # TODO
        pass

    # ── DM actions during session ────────────────────────────────────────

    def trigger_combat(self, encounter_name: str = "") -> list:
        """Force combat to start."""
        state = self.game_sm.state
        # Collect all player characters + relevant NPCs
        combatants = [self.campaign.player_character_ids]  # TODO: expand
        return self.game_sm.start_combat(combatants, encounter_name)

    def call_for_saving_throw(
        self,
        target_name: str,
        dc: int,
        ability: Ability,
        effect_on_fail: str,
        effect_on_success: str = "",
    ) -> dict:
        """DM calls for a saving throw. Engine handles the roll."""
        # TODO: wire to engine
        return {"status": "pending"}

    def apply_condition(
        self,
        target_name: str,
        condition: str,
        source: str = "",
    ) -> dict:
        """DM manually applies a condition to a target."""
        # TODO: wire to engine
        return {"status": "pending"}

    # ── DM narration control ────────────────────────────────────────────

    def set_llm_prompt(self, prompt: str) -> None:
        """Override the default LLM system prompt for this session."""
        self.dm_notes.tonight_plan = prompt


# ── Fix circular reference ─────────────────────────────────────────────────────
from dnd_core.models import DMNotes
from dnd_core.state_machine.game import GameMode